spring.application.name=Student_management
spring.datasource.url=jdbc:mysql://localhost:3306/studentportal
spring.datasource.username=root
spring.datasource.password=Loveofparis#123
spring.jpa.hibernate.ddl-auto=update